let next1 = document.querySelector('.next1')
let next2 = document.querySelector('.next2')
let next3 = document.querySelector('.next3')
let next4 = document.querySelector('.next4')
let next5 = document.querySelector('.next5')
let next6 = document.querySelector('.next6')
let next7 = document.querySelector('.next7')
let next8 = document.querySelector('.next8')
let next9 = document.querySelector('.next9')
let next10 = document.querySelector('.next10')
let next11 = document.querySelector('.next11')
let next12 = document.querySelector('.next12')
let next13 = document.querySelector('.next13')
let next14 = document.querySelector('.next14')
let next15 = document.querySelector('.next15')
let next16 = document.querySelector('.next16')
let next17 = document.querySelector('.next17')
let next18 = document.querySelector('.next18')
let next19 = document.querySelector('.next19')
let next20 = document.querySelector('.next20')
let next21 = document.querySelector('.next21')
let next22 = document.querySelector('.next22')
let next23 = document.querySelector('.next23')
let next24 = document.querySelector('.next24')

// ====================================
        // part start
// ====================================
let part1 = document.querySelector('.part1')
let part1a = document.querySelector('.part1a')
let part1b = document.querySelector('.part1b')
let part1c = document.querySelector('.part1c')
let part1d = document.querySelector('.part1d')
let part2 = document.querySelector('.part2')
let part2a = document.querySelector('.part2a')
let part2b = document.querySelector('.part2b')
let part2c = document.querySelector('.part2c')
let part2d = document.querySelector('.part2d')
let part3a = document.querySelector('.part3a')
let part3b = document.querySelector('.part3b')
let part3c = document.querySelector('.part3c')
let part3d = document.querySelector('.part3d')
let part3 = document.querySelector('.part3')
let part4a = document.querySelector('.part4a')
let part4b = document.querySelector('.part4b')
let part4c = document.querySelector('.part4c')
let part4d = document.querySelector('.part4d')
let part4 = document.querySelector('.part4')
let part5a = document.querySelector('.part5a')
let part5b = document.querySelector('.part5b')
let part5c = document.querySelector('.part5c')
let part5d = document.querySelector('.part5d')
let part5 = document.querySelector('.part5')

// ====================================
        // part end
// ====================================

let photo =document.querySelector('.photo')



next1.addEventListener('click',function(){
    part1.style.display = 'block'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
    
})

next2.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'block'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next3.addEventListener('click',function(){
    part1.style.display = 'none'        
    part1a.style.display = 'none'       
    part1b.style.display = 'block'       
    part1c.style.display = 'none'       
    part1d.style.display = 'none'       
    part2.style.display = 'none'        
    part2a.style.display = 'none'       
    part2b.style.display = 'none'       
    part2c.style.display = 'none'       
    part2d.style.display = 'none'       
    part3.style.display = 'none'        
    part3a.style.display = 'none'       
    part3b.style.display = 'none'       
    part3c.style.display = 'none'       
    part3d.style.display = 'none'       
    part4.style.display = 'none'        
    part4a.style.display = 'none'       
    part4b.style.display = 'none'       
    part4c.style.display = 'none'       
    part4d.style.display = 'none'       
    part5.style.display = 'none'        
    part5a.style.display = 'none'       
    part5b.style.display = 'none'       
    part5c.style.display = 'none'       
    part5d.style.display = 'none'       
})
next4.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'block'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next5.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'block'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next6.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'block'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next7.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'block'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next8.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'block'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next9.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'block'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next10.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'block'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next11.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'block'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next12.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'block'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next13.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'block'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next14.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'block'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next15.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'block'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next16.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'block'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next17.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'block'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next18.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'block'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next19.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'block'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next20.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'block'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next21.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'block'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next22.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'block'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next23.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'block'
    part5c.style.display = 'none'
    part5d.style.display = 'none'
})
next24.addEventListener('click',function(){
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'block'
    
})

let hider = true;
photo.addEventListener('click',function(){
   
 if(hider){
    part1.style.display ='block'
    photos.style.display ='block'
    overlayPart.style.display = 'none'
    next.style.display = 'flex'
    hider = false;
    n12.style.display = 'inline-block'

 }else{
   
    p12.style.display = 'none'
    n12.style.display = 'none'
    nextN.style.display = 'none'
    photos.style.display = 'none'
    overlayPart.style.display = 'flex'
    
    next.style.display = 'none'
    hider = true
    part1.style.display = 'none'
    part1a.style.display = 'none'
    part1b.style.display = 'none'
    part1c.style.display = 'none'
    part1d.style.display = 'none'
    part2.style.display = 'none'
    part2a.style.display = 'none'
    part2b.style.display = 'none'
    part2c.style.display = 'none'
    part2d.style.display = 'none'
    part3.style.display = 'none'
    part3a.style.display = 'none'
    part3b.style.display = 'none'
    part3c.style.display = 'none'
    part3d.style.display = 'none'
    part4.style.display = 'none'
    part4a.style.display = 'none'
    part4b.style.display = 'none'
    part4c.style.display = 'none'
    part4d.style.display = 'none'
    part5.style.display = 'none'
    part5a.style.display = 'none'
    part5b.style.display = 'none'
    part5c.style.display = 'none'
 }
})

let overlayPart = document.querySelector('.overlayPart')
let next = document.querySelector('.next')
let photos =document.querySelector('.photos')
let n12 = document.querySelector('.n12')
let p12 = document.querySelector('.p12')
let nextN = document.querySelector('.nextN')

n12.addEventListener('click',function(){
    p12.style.display ='inline-block'
    n12.style.display ='none'
    next.style.display = 'none'
    nextN.style.display = 'flex'
})
p12.addEventListener('click',function(){
    n12.style.display ='inline-block'
    p12.style.display ='none'
    next.style.display = 'flex'
    nextN.style.display = 'none'
})